"""First-run setup: udev rule, WirePlumber rule, audio service."""

import os
import shutil
import subprocess
import tempfile
import threading

from . import paths, service

UDEV_RULES = (
    'SUBSYSTEM=="usb", ATTR{idVendor}=="0fd9", ATTR{idProduct}=="007d", MODE="0666"',  # Wave XLR
    'SUBSYSTEM=="usb", ATTR{idVendor}=="0fd9", ATTR{idProduct}=="00a6", MODE="0666"',  # Wave XLR MK.2
    'SUBSYSTEM=="usb", ATTR{idVendor}=="0fd9", ATTR{idProduct}=="0070", MODE="0666"',  # Wave:3
)
UDEV_PATH = "/etc/udev/rules.d/99-openwave.rules"
UDEV_PATH_OLD = "/etc/udev/rules.d/99-wavexlr.rules"

WIREPLUMBER_NAME = "51-openwave-wave-xlr.conf"
WIREPLUMBER_PATH = os.path.expanduser(
    "~/.config/wireplumber/wireplumber.conf.d/" + WIREPLUMBER_NAME
)

MIXES_NAME = "52-openwave-mixes.conf"
MIXES_PATH = os.path.expanduser(
    "~/.config/pipewire/pipewire.conf.d/" + MIXES_NAME
)


def wireplumber_source():
    return paths.data_file("wireplumber", WIREPLUMBER_NAME)


def mixes_source():
    return paths.data_file("pipewire", MIXES_NAME)


def udev_installed():
    for path in (UDEV_PATH, UDEV_PATH_OLD):
        try:
            with open(path) as f:
                content = f.read()
            if all(pid in content for pid in ("007d", "0070")):
                return True
        except (FileNotFoundError, PermissionError):
            continue
    return False


def service_installed():
    return service.is_installed()


def service_needs_refresh():
    """Whether an installed service still starts the daemon this install ships.

    Separate from service_installed() so run_uninstall() keeps removing a unit
    that has gone stale, which a stricter service_installed() would make it
    walk past and leave enabled.
    """
    return service.needs_refresh()


def wireplumber_installed():
    try:
        with open(WIREPLUMBER_PATH) as f:
            installed = f.read()
    except OSError:
        return False
    src = wireplumber_source()
    if src is None:
        return True
    try:
        with open(src) as f:
            return f.read() == installed
    except OSError:
        return True


def mixes_installed():
    return os.path.exists(MIXES_PATH)


def needs_setup():
    return (
        not udev_installed()
        or not service_installed()
        or service_needs_refresh()
        or not wireplumber_installed()
        or not mixes_installed()
    )


def install_udev():
    """Install udev rules via pkexec."""
    rules = "\n".join(UDEV_RULES)
    script = f"""#!/bin/sh
cat > {UDEV_PATH} <<'EOF'
{rules}
EOF
udevadm control --reload-rules
udevadm trigger --subsystem-match=usb --attr-match=idVendor=0fd9 --attr-match=idProduct=007d
udevadm trigger --subsystem-match=usb --attr-match=idVendor=0fd9 --attr-match=idProduct=0070
udevadm trigger --subsystem-match=usb --attr-match=idVendor=0fd9 --attr-match=idProduct=00a6
# Also chmod the device node directly so no replug is needed
for dev in /dev/bus/usb/*/; do
    for f in "$dev"*; do
        if udevadm info --query=property "$f" 2>/dev/null | grep -q 'ID_VENDOR_ID=0fd9'; then
            chmod 0666 "$f"
        fi
    done
done
"""
    tmp = "/tmp/openwave-udev-setup.sh"
    with open(tmp, "w") as f:
        f.write(script)
    os.chmod(tmp, 0o755)

    r = subprocess.run(["pkexec", tmp], capture_output=True, text=True)
    os.unlink(tmp)
    return r.returncode == 0


def install_service():
    """Install and enable the audio service via the active backend."""
    service.install()
    return True


def install_wireplumber():
    """Drop the suspend-disable rule into the user's WirePlumber config."""
    src = wireplumber_source()
    if src is None:
        raise FileNotFoundError(
            f"WirePlumber rule source not found: share/openwave/wireplumber/"
            f"{WIREPLUMBER_NAME} is missing from this install"
        )
    with open(src) as f:
        content = f.read()
    os.makedirs(os.path.dirname(WIREPLUMBER_PATH), exist_ok=True)
    with open(WIREPLUMBER_PATH, "w") as f:
        f.write(content)
    return True


# install_mixes writes one shared file and shells out to pw-cli. Two mix
# operations overlapping would interleave both, so every call serialises here.
_INSTALL_LOCK = threading.Lock()


def _spa_str(value):
    """Quote a string as a SPA-JSON / PipeWire config value.

    Mix descriptions are typed by the user and reach both the generated config
    and a pw-cli argument. An unescaped quote or backslash truncates the
    property and corrupts every sink defined after it, and because the config
    is regenerated from the stored name, renaming the mix cannot repair it --
    so the escaping belongs at render time, not at creation time.
    """
    return '"' + str(value).replace("\\", "\\\\").replace('"', '\\"') + '"'


GENERATED_MARKER = "# GENERATED by OpenWave"

MIXES_HEADER = GENERATED_MARKER + """ from ~/.config/openwave/mixdefs.json.
#
# Hand edits are overwritten whenever a mix is added, renamed or removed.
# Edit mixes in the app instead.
#
# Each mix is a null sink: applications play into it, and OpenWave carries its
# monitor to an output device (or not, for a mix that is only captured).
"""


def render_mixes_conf(mixes):
    """Render the PipeWire config defining every mix sink."""
    entries = []
    for mix in mixes.values():
        entries.append(
            "    {   factory = adapter\n"
            "        args = {\n"
            "            factory.name      = support.null-audio-sink\n"
            f"            node.name         = {mix['sink']}\n"
            "            node.description  = "
            + _spa_str(mix["description"]) + "\n"
            "            media.class       = Audio/Sink\n"
            "            audio.position    = [ FL FR ]\n"
            "            object.linger     = true\n"
            "            monitor.channel-volumes = true\n"
            # A mix master is OpenWave's to remember. WirePlumber's
            # restore-stream tracks these sinks on some setups (its
            # stream-properties carries Audio/Sink entries for them) and
            # re-applies its own last-seen level when the sink reappears --
            # racing, and usually beating, the restore OpenWave does from
            # mixes.json. One value wins on one boot and the other on the
            # next, which reads as levels reverting at random.
            "            state.restore-props = false\n"
            "        }\n"
            "    }\n"
        )
    return MIXES_HEADER + "\ncontext.objects = [\n" + "".join(entries) + "]\n"


def _mix_sink_exists(name):
    """Return True if a PipeWire/Pulse sink with this name is already live."""
    try:
        r = subprocess.run(
            ["pactl", "list", "short", "sinks"],
            capture_output=True, text=True, timeout=3,
        )
    except (FileNotFoundError, subprocess.SubprocessError):
        return False
    return any(line.split("\t", 2)[1] == name for line in r.stdout.splitlines() if "\t" in line)


def list_sink_names(prefix=""):
    """Live sink node names, optionally filtered by prefix."""
    try:
        r = subprocess.run(
            ["pactl", "list", "short", "sinks"],
            capture_output=True, text=True, timeout=3,
        )
    except (FileNotFoundError, subprocess.SubprocessError):
        return []
    names = []
    for line in r.stdout.splitlines():
        parts = line.split("\t")
        if len(parts) > 1 and parts[1].startswith(prefix):
            names.append(parts[1])
    return names


def create_null_sink(name, description, priority=None):
    """Public name for the null-sink creator: mixes are not its only user.

    Application sources need one each as a stream intake, and they are created
    on exactly the same terms -- object.linger is mandatory, because without it
    the node dies the moment pw-cli exits.
    """
    _create_mix_sink_live(name, description, priority=priority)


def _create_mix_sink_live(name, description, priority=None):
    """Spawn a null sink immediately so it appears without a PipeWire restart."""
    if _mix_sink_exists(name):
        return
    props = [
        "factory.name=support.null-audio-sink",
        f"node.name={name}",
        "node.description=" + _spa_str(description),
        "media.class=Audio/Sink",
        "audio.position=[FL FR]",
        # Mandatory: without it the node dies the moment pw-cli exits.
        "object.linger=true",
        # Without this a null sink's monitor is taken PRE-volume, so the sink's
        # volume changes nothing downstream -- measured, at volume 0 the
        # monitor read full scale rather than silence. The generated config
        # sets it on every mix sink; this path makes the same kind of node and
        # must match, or a source's level slider does nothing.
        "monitor.channel-volumes=true",
    ]
    if priority is not None:
        # Session priority decides which sink the session manager picks as the
        # system default. An intake sink is internal plumbing and must never
        # win that election: as the default it swallows every application into
        # one source row, at that row's send level.
        props.append(f"priority.session={int(priority)}")
    args = "{ " + " ".join(props) + " }"
    try:
        subprocess.run(
            ["pw-cli", "create-node", "adapter", args],
            capture_output=True, text=True, timeout=5,
        )
    except (FileNotFoundError, subprocess.SubprocessError):
        # pw-cli unavailable or PipeWire not reachable — the config file
        # we just wrote will take effect on next PipeWire load.
        pass


def destroy_mix_sink(name):
    """Destroy every live PipeWire node published under this node.name.

    Two nodes can share a node.name — the config-file sink and one created by
    a previous session's pw-cli create-node both carry it — so every match is
    destroyed, not just the first one found.

    Shells out to pw-dump and pw-cli with multi-second timeouts. Call this from
    the mixer worker thread only; on the GTK main thread it freezes the window
    for as long as PipeWire takes to answer.
    """
    import json as _json
    try:
        r = subprocess.run(["pw-dump"], capture_output=True, text=True, timeout=5)
        if r.returncode != 0:
            return False
        objects = _json.loads(r.stdout)
    except (FileNotFoundError, subprocess.SubprocessError, _json.JSONDecodeError):
        return False

    node_ids = [
        obj["id"] for obj in objects
        if obj.get("type") == "PipeWire:Interface:Node"
        and obj.get("id") is not None
        and (((obj.get("info") or {}).get("props") or {}).get("node.name") == name)
    ]

    destroyed = False
    for node_id in node_ids:
        try:
            r = subprocess.run(
                ["pw-cli", "destroy", str(node_id)],
                capture_output=True, text=True, timeout=5,
            )
        except (FileNotFoundError, subprocess.SubprocessError):
            continue
        destroyed = destroyed or r.returncode == 0
    return destroyed


def install_mixes(mixes=None):
    """Write the generated mix config and materialise the sinks.

    Refuses to write an empty config: the caller's store may have failed to
    load, and an empty render would silently delete every mix sink.
    """
    if mixes is None:
        from . import mixes as mixes_module
        mixes = mixes_module.load_seeded()
    if not mixes:
        return False
    with _INSTALL_LOCK:
        return _install_mixes_locked(mixes)


def _install_mixes_locked(mixes):
    """install_mixes' body, run with _INSTALL_LOCK held."""
    content = render_mixes_conf(mixes)
    os.makedirs(os.path.dirname(MIXES_PATH), exist_ok=True)

    # Preserve a hand-written config once, before the first generated write
    # replaces it. The same directory already uses the .bak convention.
    if os.path.exists(MIXES_PATH):
        try:
            with open(MIXES_PATH) as f:
                existing = f.read()
        except OSError:
            existing = GENERATED_MARKER
        if GENERATED_MARKER not in existing and not os.path.exists(MIXES_PATH + ".bak"):
            try:
                shutil.copy2(MIXES_PATH, MIXES_PATH + ".bak")
            except OSError:
                pass
        if existing == content:
            for mix in mixes.values():
                _create_mix_sink_live(mix["sink"], mix["description"])
            return True

    fd, tmp = tempfile.mkstemp(dir=os.path.dirname(MIXES_PATH), prefix=".mixes-")
    try:
        with os.fdopen(fd, "w") as f:
            f.write(content)
        os.replace(tmp, MIXES_PATH)
    except BaseException:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise

    for mix in mixes.values():
        _create_mix_sink_live(mix["sink"], mix["description"])
    return True


def run_setup():
    """Run full first-time setup. Returns (success, message)."""
    messages = []

    if not udev_installed():
        if install_udev():
            messages.append("USB permissions configured")
        else:
            return False, "Failed to set up USB permissions (pkexec cancelled?)"

    # Install the WirePlumber rule before starting the service so the daemon's
    # pw-cat attaches to a node that already has suspend disabled.
    if not wireplumber_installed():
        try:
            install_wireplumber()
            messages.append(
                "WirePlumber rule installed (restart wireplumber to apply)"
            )
        except Exception as e:
            return False, f"Failed to install WirePlumber rule: {e}"

    if not mixes_installed():
        try:
            install_mixes()
            messages.append(
                "Mix sinks installed (restart PipeWire to apply)"
            )
        except Exception as e:
            return False, f"Failed to install mix sinks: {e}"

    if not service_installed():
        try:
            install_service()
            messages.append("Audio service installed and started")
        except Exception as e:
            return False, f"Failed to install service: {e}"
    elif service_needs_refresh():
        try:
            install_service()
            messages.append("Audio service updated for this install")
        except Exception as e:
            return False, f"Failed to update service: {e}"

    return True, ". ".join(messages) if messages else "Already configured"


def uninstall_service():
    """Stop, disable, and remove the audio service via the active backend."""
    service.uninstall()


def uninstall_wireplumber():
    """Remove the WirePlumber rule from the user's config."""
    try:
        os.unlink(WIREPLUMBER_PATH)
    except FileNotFoundError:
        return False
    return True


def uninstall_mixes():
    """Remove the mix sinks config from the user's PipeWire config."""
    try:
        os.unlink(MIXES_PATH)
    except FileNotFoundError:
        return False
    return True


def uninstall_udev():
    """Remove udev rule via pkexec."""
    script = f"""#!/bin/sh
rm -f {UDEV_PATH} {UDEV_PATH_OLD}
udevadm control --reload-rules
"""
    tmp = "/tmp/openwave-udev-remove.sh"
    with open(tmp, "w") as f:
        f.write(script)
    os.chmod(tmp, 0o755)
    r = subprocess.run(["pkexec", tmp], capture_output=True, text=True)
    try:
        os.unlink(tmp)
    except FileNotFoundError:
        pass
    return r.returncode == 0


def run_uninstall():
    """Remove capture fix service, WirePlumber rule, and udev rule. Returns (success, message)."""
    messages = []

    if service_installed():
        try:
            uninstall_service()
            messages.append("Audio service removed")
        except Exception as e:
            return False, f"Failed to remove service: {e}"

    if wireplumber_installed():
        if uninstall_wireplumber():
            messages.append("WirePlumber rule removed")

    if mixes_installed():
        if uninstall_mixes():
            messages.append("Mix sinks removed")

    if udev_installed():
        if uninstall_udev():
            messages.append("USB permissions removed")
        else:
            return False, "Failed to remove USB permissions (pkexec cancelled?)"

    return True, ". ".join(messages) if messages else "Already uninstalled"
